### ISSUE TITLE
Crash when using the first time, because get_entry returns no username.

### ISSUE THREAD

**Issue by doxygen-spammer** [epwr/git-credential-with-kwallet#2]
There are these lines in `get`, which cause a crash when there are no credentials in the KWallet yet:

```ruby
    value = get_entry(wallet_id, KWALLET_FOLDER, creds["host"])
    username_length = value.match(/^\d+-/)[0][0..-2].to_i
```

I don’t know Ruby, but it looks to me that get_entry does not find an entry in the KWallet, therefore returns some kind of empty value, therefore `match` returns an empty value, which does not provide the `[]` method.

This is the crash message which I get:

```
$ git push -u origin master
Traceback (most recent call last):
        2: from /home/david/.bin/git-credential-with-kwallet:216:in `<main>'
        1: from /home/david/.bin/git-credential-with-kwallet:202:in `run'
/home/doxy/.bin/git-credential-with-kwallet:146:in `get': undefined method `[]' for nil:NilClass (NoMethodError)
Username for 'https://github.com': [...]
```

However, despite this one-time crash message, the tool does its job fine. :)

**Comment by epwr** [comment]
Thanks for the bug report! Working on a fix, should have it out in a few minutes.
