### ISSUE TITLE
"No such file or directory" error

### ISSUE THREAD

**Issue by pablos-here** [epwr/git-credential-with-kwallet#3]
Hi,

I'm getting a stack trace on a `git push`.  I'm on a rolling distro so it's possible the _leading edge_ is the _bleeding edge_.  :)

Thx!

**Stack trace**
```
$ git push
/home/pablo/bin/git-credential-with-kwallet:36:in ``': No such file or directory - qdbus (Errno::ENOENT)
        from /home/pablo/bin/git-credential-with-kwallet:36:in `run_kwd5'
        from /home/pablo/bin/git-credential-with-kwallet:60:in `get_wallet_id'
        from /home/pablo/bin/git-credential-with-kwallet:144:in `get'
        from /home/pablo/bin/git-credential-with-kwallet:205:in `run'
        from /home/pablo/bin/git-credential-with-kwallet:219:in `<main>'
/home/pablo/bin/git-credential-with-kwallet:36:in ``': No such file or directory - qdbus (Errno::ENOENT)
        from /home/pablo/bin/git-credential-with-kwallet:36:in `run_kwd5'
        from /home/pablo/bin/git-credential-with-kwallet:60:in `get_wallet_id'
        from /home/pablo/bin/git-credential-with-kwallet:179:in `erase'
        from /home/pablo/bin/git-credential-with-kwallet:209:in `run'
        from /home/pablo/bin/git-credential-with-kwallet:219:in `<main>'
```

**Comment by epwr** [comment]
Hey! 

Looks like `qdbus` isn't found anywhere in your path. What distro are you using?

E

**Comment by epwr** [comment]
Added cleaner error handling for this, hoping that helps :)

I'm closing this issue, but please comment if this doesn't address your issue and I'll re-open this.

**Comment by pablos-here** [comment]
Hi!
Thank you for the quick response.  I'm on `openSUSE Tumbleweed` and I confirmed on `openSUSE MicroOS`, both use `qdbus-qt5`.

I did a search-and-replace for `qdbus` with `qdbus-qt5` and it addressed the issue.  However, would you consider adding to the global variable section, say, `QDBUS = "qdbus"`.  Perhaps update the `README.md` accordingly?  Or heck, I'd be happy to submit a PR with an update to the `README.md`.  The least I could do!  

Whaddya think?

Thx so much!

**Comment by epwr** [comment]
Oh interesting! I think I've implemented a fix (the program will try to find both executables) and updated the README accordingly. Would you see if that fixes it for you?

& no problem! It's cool to have others using this.

**Comment by pablos-here** [comment]
I've confirmed that the fix is solid.  Thank you again for the rapid response!   :)
